'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ANSI_ASCII_Converter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property arrowdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrowup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property ASCIIUnicodeConverter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ASCIIUnicodeConverter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property BassMOD_Net() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BassMOD_Net", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Public ReadOnly Property BG25pxg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG25pxg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property CHSAC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHSAC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property dossifont2b1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dossifont2b1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property FormBg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FormBg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property JESPERK() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("JESPERK", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Public ReadOnly Property PanelBgRev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PanelBgRev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property RoORS() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RoORS", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property RoyAvt6faster1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RoyAvt6faster1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property RoySAC() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("RoySAC", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
